apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-gke

spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-client-gke
  template:
    metadata:
      labels:
        app: grpc-client-gke
    spec:
      containers:
      - name: grpc-client-gke
        image: gcr.io/grpc-client-305816/grpc-client-image:latest
        ports:
        - containerPort: 8080